# Generated by Django 3.1.3 on 2020-12-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.CharField(blank=True, max_length=264),
        ),
    ]
