# Generated by Django 3.1.3 on 2020-12-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Video', '0004_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name_plural': 'Comments'},
        ),
        migrations.AddField(
            model_name='comments',
            name='comment',
            field=models.TextField(blank=True, max_length=264),
        ),
    ]
