# Generated by Django 3.1.3 on 2020-12-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Video', '0005_auto_20201217_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(max_length=264),
        ),
    ]
